// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbihuzretjxfjxkczrkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiaWh1enJldGp4Zmp4a2N6cmtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMTAyNTIsImV4cCI6MjA2Mzg4NjI1Mn0.9oSFXOtqwUii2L_trbppm2PXMy4cET75DymFXuGN-LY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);