// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgpvgyqbngkrqjgcwxzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRncHZneXFibmdrcnFqZ2N3eHp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNTQ5OTIsImV4cCI6MjA2MzYzMDk5Mn0.Yf-Goxo1faNaoXOnEoN9IkRm-rhkO22qOd4m1VVQMM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);